language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis CI 서버의 Home 푸쉬 확인3
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r portfolio *
  - mkdir -p deploy
  - mv portfolio.zip deploy/portfolio.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: parkinglot-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: parkinglot-bucket
    key: portfolio.zip
    bundle_type: zip
    application: portfoliocodedeploy
    deployment_group: portfoliocodedeploy
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hongs7701@naver.com