# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: portfolio CI/CD with Gradle

# 'master' branch에 push와 pull 이루이지면 작업 진행
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    #(1)Spring Boot 어플리케이션 Build
    - name: Spring Boot Build
      run: ./gradlew clean build -x test

    #(2)Docker 이미지 Build
    - name: docker image build
      run: docker build -t meanofredstone/portfolio .

    #(3)DockerHub Login
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    #(4)DockerHub Push
    - name: docker Hub push
      run: docker push meanofredstone/portfolio
